request:
  \MagmaCore\Http\RequestHandler
response:
  \MagmaCore\Http\ResponseHandler
restful:
  \MagmaCore\RestFul\RestHandler
formBuilder:
  \MagmaCore\FormBuilder\FormBuilder
eventDispatcher:
  \MagmaCore\EventDispatcher\EventDispatcher
error:
  \MagmaCore\Error\Error
tableGrid:
  \MagmaCore\Datatable\Datatable
collection:
  \MagmaCore\Collection\Collection
global:
  \MagmaCore\Session\GlobalManager\GlobalManager
flatDb:
  \MagmaCore\DataObjectLayer\FileStorageRepository\FileStorage
FlatRepository:
  \MagmaCore\DataObjectLayer\FileStorageRepository\FileStorageRepository
controllerSettings:
  \MagmaCore\Settings\Model\ControllerSettingModel
settings:
  \MagmaCore\Settings\Settings
widgetFactory:
  \MagmaCore\Widget\WidgetFactory